//package sbz.project
//
//import sbz.project.Application.domain.facts.*;
//
//rule "ADD_MALT_TO_MASH_TUN ALARM"
//    when
//        $a: Action(type == "ADD_MALT_TO_MASH_TUN");
//        not (
//            Measurer(name == "MEASURER_MASH_TUN_MALT")
//            over window:time(10s)
//        )
//    then
//        System.out.println("[ALARM] MEASURER_MASH_TUN_MALT - NOT WORKING");
//        insert(new Alarm("[ALARM] MEASURER_MASH_TUN_MALT", "NOT WORKING"));
//        drools.halt();
//end