package sbz.project

import sbz.project.Application.domain.facts.*;
import java.util.List

rule "Stop releasing mixture to launter tan"
    when
        $a: Action(type == "RELEASE_MIXTURE_TO_LAUNTER_TAN");
    then
        System.out.println("STOP_RELEASING_MIXTURE_TO_LAUNTER_TAN");
        insert(new Action("STOP_RELEASING_MIXTURE_TO_LAUNTER_TAN"));
end

rule "Add water to launter tan"
    when
        $a: Action(type == "STOP_RELEASING_MIXTURE_TO_LAUNTER_TAN" || type == "RELEASE_MIXTURE_TO_LAUNTER_TAN_FOR_SECOND_TIME");
    then
        System.out.println("ADD_WATER_TO_LAUNTER_TAN");
        insert(new Action("ADD_WATER_TO_LAUNTER_TAN"));

end

rule "Stop adding water to launter tan"
    when
        $a: Action(type == "ADD_WATER_TO_LAUNTER_TAN");
    then
        System.out.println("STOP_ADDING_WATER_TO_LAUNTER_TAN");
        insert(new Action("STOP_ADDING_WATER_TO_LAUNTER_TAN"));
end

rule "Release back mixture to pre launter tan and release mixture tu pre launter"
    when
        $a: Action(type == "STOP_ADDING_WATER_TO_LAUNTER_TAN");
        $list: List(size == 0) from collect (Action(type == "RELEASE_MIXTURE_TO_LAUNTER_TAN_FOR_SECOND_TIME"))
    then
       System.out.println("RELEASE_MIXTURE_TO_PRE_LAUNTER_TAN");
       insert(new Action("RELEASE_MIXTURE_TO_PRE_LAUNTER_TAN"));
       System.out.println("RELEASE_BACK_MIXTURE_TO_PRE_LAUNTER_TAN");
    insert(new Action("RELEASE_BACK_MIXTURE_TO_PRE_LAUNTER_TAN"));
end

rule "Stop releasing mixture to pre launter tan"
    when
        $a: Action(type == "RELEASE_BACK_MIXTURE_TO_PRE_LAUNTER_TAN");
    then
        System.out.println("STOP_RELEASING_BACK_MIXTURE_TO_PRE_LAUNTER_TAN");
        insert(new Action("STOP_RELEASING_BACK_MIXTURE_TO_PRE_LAUNTER_TAN"));
end

rule "Start separating wort from the grains"
    when
        $a: Action(type == "RELEASE_MIXTURE_TO_LAUNTER_TAN_FOR_SECOND_TIME");
        $list: List(size == 2) from collect (Action(type == "ADD_WATER_TO_LAUNTER_TAN"))
    then
        System.out.println("START_SEPARATING_WORT_FROM_THE_GRAINS");
        insert(new Action("START_SEPARATING_WORT_FROM_THE_GRAINS"));
end


rule "Stop separating wort from the grains"
    when
        $a: Action(type == "START_SEPARATING_WORT_FROM_THE_GRAINS");
    then
        System.out.println("STOP_SEPARATING_WORT_FROM_THE_GRAINS");
        insert(new Action("STOP_SEPARATING_WORT_FROM_THE_GRAINS"));
end

rule "Release wort and hops to brew kettle"
    when
        $a: Action(type == "STOP_SEPARATING_WORT_FROM_THE_GRAINS");
    then
        System.out.println("RELEASE_WORT_TO_BREW_KETTLE");
        insert(new Action("RELEASE_WORT_TO_BREW_KETTLE"));
        System.out.println("ADD_HOPS_TO_BREW_KETTLE");
        insert(new Action("ADD_HOPS_TO_BREW_KETTLE"));
        System.out.println("phase five started!");
end

rule "Stop releasing wort to brew kettle"
    when
        $a: Action(type == "RELEASE_WORT_TO_BREW_KETTLE");
    then
        System.out.println("STOP_RELEASING_WORT_TO_BREW_KETTLE");
        insert(new Action("STOP_RELEASING_WORT_TO_BREW_KETTLE"));
        System.out.println("phase four done!");

end
