package sbz.project

import sbz.project.Application.domain.facts.*;
import java.util.List


rule "Start filling barrels"
    when
        $a: Action(type == "START_FILTERING");
    then
        System.out.println("phase twelve started!");
        System.out.println("START_FILLING_BARRELS");
        insert(new Action("START_FILLING_BARRELS"));
end


rule "Stop filling barrels"
    when
        $a: Action(type == "START_FILLING_BARRELS");
    then
        System.out.println("STOP_FILLING_BARRELS");
        insert(new Action("STOP_FILLING_BARRELS"));
        System.out.println("phase twelve done!");
end