package sbz.project

import sbz.project.Application.domain.facts.*;

rule "Stop adding malt to mash tun"
    when
        $a: Action(type == "ADD_MALT_TO_MASH_TUN");
    then
        System.out.println("STOP_ADDING_MALT_TO_MASH_TUN");
        insert(new Action("STOP_ADDING_MALT_TO_MASH_TUN"));
end

rule "Add water to mash tun"
    when
        $a: Action(type == "STOP_ADDING_MALT_TO_MASH_TUN");
    then
        System.out.println("ADD_WATER_TO_MASH_TUN");
        insert(new Action("ADD_WATER_TO_MASH_TUN"));
end

rule "Stop adding water to mash tun"
    when
        $a: Action(type == "ADD_WATER_TO_MASH_TUN");
    then
        System.out.println("STOP_ADDING_WATER_TO_MASH_TUN");
        insert(new Action("STOP_ADDING_WATER_TO_MASH_TUN"));
end

rule "Start mashing"
    when
        $a: Action(type == "STOP_ADDING_WATER_TO_MASH_TUN");
    then
        System.out.println("START_MASHING");
        insert(new Action("START_MASHING"));
end


rule "Stop mashing"
    when
        $a: Action(type == "START_MASHING");
    then
        System.out.println("STOP_MASHING");
        insert(new Action("STOP_MASHING"));
        System.out.println("phase two done!");
end

rule "Release mixture"
    when
        $a: Action(type == "STOP_MASHING");
    then
        System.out.println("RELEASE_MIXTURE_TO_PRE_LAUNTER_TAN");
        insert(new Action("RELEASE_MIXTURE_TO_PRE_LAUNTER_TAN"));
        System.out.println("phase three started!");

end


