package sbz.project

import sbz.project.Application.domain.facts.*;
import java.util.List

global sbz.project.Application.service.action.ActionService actionService;

rule "Add yeast"
    when
        $a: Action(type == "CLOSE_FERMENTATION_VESSELS");
    then
        delete($a);
        System.out.println("ADD_YEAST");
        insert(new Action("ADD_YEAST"));
        actionService.sendMessage("ADD_YEAST");
end

rule "Stop adding yeast"
    when
        $a: Action(type == "ADD_YEAST");
        $m: Measurer(name == "MEASURER_YEAST", value == 20);
    then
        delete($a);
        System.out.println("STOP_ADDING_YEAST");
        insert(new Action("STOP_ADDING_YEAST"));
        actionService.sendMessage("STOP_ADDING_YEAST");
end

rule "Begin fermentation"
    when
        $a: Action(type == "STOP_ADDING_YEAST");
    then
        delete($a);
        System.out.println("BEGIN_FERMENTATION");
        long time = 3000;
        actionService.startAction(time, "BEGIN_FERMENTATION");
end

rule "Stop fermentation"
    when
        $a: Action(type == "BEGIN_FERMENTATION");
    then
        delete($a);
        System.out.println("STOP_FERMENTATION");
        insert(new Action("STOP_FERMENTATION"));
        System.out.println("phase eight done!");
end

rule "Release beer to conditioning tank"
    when
        $a: Action(type == "STOP_FERMENTATION");
    then
        delete($a);
        System.out.println("phase nine started!");
        System.out.println("RELEASE_BEER_TO_CONDITIONING_TANK");
        insert(new Action("RELEASE_BEER_TO_CONDITIONING_TANK"));
        actionService.sendMessage("RELEASE_BEER_TO_CONDITIONING_TANK");
end


rule "Stop releasing beer to conditioning tank"
    when
        $a: Action(type == "RELEASE_BEER_TO_CONDITIONING_TANK");
        $m: Measurer(name == "MEASURER_FERMENTATION_TANK", value == 0);
    then
        delete($a);
        System.out.println("STOP_RELEASING_BEER_TO_CONDITIONING_TANK");
        insert(new Action("STOP_RELEASING_BEER_TO_CONDITIONING_TANK"));
        actionService.sendMessage("STOP_RELEASING_BEER_TO_CONDITIONING_TANK");
end