package sbz.project

import sbz.project.Application.domain.facts.*;
import java.util.List

rule "Start bottling"
    when
        $a: Action(type == "START_FILTERING");
    then
        System.out.println("phase eleven started!");
        System.out.println("START_BOTTLING");
        insert(new Action("START_BOTTLING"));
end

rule "Stop bottling"
    when
        $a: Action(type == "START_BOTTLING");
        $m: Measurer(name == "MEASURER_CONDITIONING_TANK", value == 0);
    then
        delete($a);
        System.out.println("STOP_BOTTLING");
        insert(new Action("STOP_BOTTLING"));
        System.out.println("phase eleven done!");

end