package sbz.project

import sbz.project.Application.domain.facts.*;
import java.util.List
global sbz.project.Application.service.action.ActionService actionService;


//rule "Stop releasing hops to brew kettle"
//    when
//        $a: Action(type == "ADD_HOPS_TO_BREW_KETTLE");
//        $m: Measurer(name == "MEASURER_BREW_KETTLE_HOPS", value == 10)
//    then
//        delete($a);
//        System.out.println("STOP_ADDING_HOPS_TO_BREW_KETTLE");
//        insert(new Action("STOP_ADDING_HOPS_TO_BREW_KETTLE"));
//        actionService.sendMessage("STOP_ADDING_HOPS_TO_BREW_KETTLE");
//end

//rule "Start boiling"
//    when
//        $a: Action(type == "STOP_ADDING_HOPS_TO_BREW_KETTLE");
//        $a2: Action(type == "STOP_RELEASING_WORT_TO_BREW_KETTLE");
//    then
//        delete($a);
//        System.out.println("START_BOILING");
//        long time = 3000;
//        actionService.startAction(time, "START_BOILING");
//end

rule "Stop boiling"
    when
        $a: Action(type == "START_BOILING");
    then
        delete($a);
        System.out.println("STOP_BOILING");
        insert(new Action("STOP_BOILING"));
        System.out.println("phase five done!");
end


rule "Release wort to whirlpool "
    when
        $a: Action(type == "STOP_BOILING");
    then
        delete($a);
        System.out.println("RELEASE_WORT_TO_WHIRLPOOL");
        insert(new Action("RELEASE_WORT_TO_WHIRLPOOL"));
        actionService.sendMessage("RELEASE_WORT_TO_WHIRLPOOL");
end

rule "Stop releasing wort to whirlpool "
    when
        $a: Action(type == "RELEASE_WORT_TO_WHIRLPOOL");
        $m: Measurer(name == "MEASURER_BREW_KETTLE", value == 0);
    then
        delete($a);
        System.out.println("STOP_RELEASING_WORT_TO_WHIRLPOOL");
        insert(new Action("STOP_RELEASING_WORT_TO_WHIRLPOOL"));
        actionService.sendMessage("STOP_RELEASING_WORT_TO_WHIRLPOOL");
end