package sbz.project


import sbz.project.Application.domain.facts.*;
import sbz.project.Application.domain.enums.Unit;
import sbz.project.Application.util.DateUtil.*;
import java.util.Date
import sbz.project.Application.service.*;

global sbz.project.Application.service.action.ActionService actionService;

rule "Stop adding malt to mash tun"
    when
        $a: Action(type == "ADD_MALT_TO_MASH_TUN");
        $m: Measurer(name == "MEASURER_MASH_TUN_MALT", value == 20, unit == Unit.KILOGRAM);
    then
        System.out.println("STOP_ADDING_MALT_TO_MASH_TUN");
        insert(new Action("STOP_ADDING_MALT_TO_MASH_TUN"));
        actionService.sendMessage("STOP_ADDING_MALT_TO_MASH_TUN");
        delete($a);
end

rule "Add water to mash tun"
    when
        $a: Action(type == "STOP_ADDING_MALT_TO_MASH_TUN");
    then
        System.out.println("ADD_WATER_TO_MASH_TUN");
        insert(new Action("ADD_WATER_TO_MASH_TUN"));
        actionService.sendMessage("ADD_WATER_TO_MASH_TUN");
        delete($a);
end

//rule "Stop adding water to mash tun"
//    when
//        $a: Action(type == "ADD_WATER_TO_MASH_TUN");
//        $m: Measurer(name == "MEASURER_MASH_TUN_WATER", value == 70, unit == Unit.LITER);
//    then
//        System.out.println("STOP_ADDING_WATER_TO_MASH_TUN");
//        insert(new Action("STOP_ADDING_WATER_TO_MASH_TUN"));
//        actionService.sendMessage("STOP_ADDING_WATER_TO_MASH_TUN");
//        delete($a);
//end

rule "Start mashing"
    when
        $a: Action(type == "STOP_ADDING_WATER_TO_MASH_TUN");
    then
        System.out.println("START_MASHING");
//        long time = 1000 * 60 * 60; // 1h
        long time = 5000;
        delete($a);

        actionService.startAction(time, "START_MASHING");
end

rule "Stop mashing"
    when
        $a: Action(type == "START_MASHING");
    then
        delete($a);
        System.out.println("STOP_MASHING");
        insert(new Action("STOP_MASHING"));
        System.out.println("phase two done!");
end

rule "Release mixture to pre launter tun"
    when
        $a: Action(type == "STOP_MASHING");
    then
        delete($a);
        System.out.println("RELEASE_MIXTURE_TO_PRE_LAUNTER_TUN");
        insert(new Action("RELEASE_MIXTURE_TO_PRE_LAUNTER_TUN"));
        actionService.sendMessage("RELEASE_MIXTURE_TO_PRE_LAUNTER_TUN");
        System.out.println("phase three started!");

end


