package sbz.project;

import sbz.project.Application.domain.facts.*;
global sbz.project.Application.service.action.ActionService actionService;

rule "Start system"
    when
        $a: Action(type == "START_SYSTEM")
    then
        System.out.println("phase two started!");
        System.out.println("ADD_MALT_TO_MASH_TUN)");
        insert(new Action("ADD_MALT_TO_MASH_TUN"));
        actionService.sendMessage("ADD_MALT_TO_MASH_TUN");
end