package sbz.project

import sbz.project.Application.domain.facts.*;
import java.util.List;
global sbz.project.Application.service.action.ActionService actionService;

//rule "Stop releasing mixture"
//    when
//        $a: Action(type == "RELEASE_MIXTURE_TO_PRE_LAUNTER_TUN");
//        $m: Measurer(name == "MEASURER_MASH_TUN", value == 30);
//        $m2: Measurer(name == "MEASURER_PRE_LAUNTER_TUN", value == 60);
//    then
//        delete($a);
//        System.out.println("STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN");
//        insert(new Action("STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN"));
//        actionService.sendMessage("STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN");
//end


rule "Stop releasing mixture for second time"
    when
        $a: Action(type == "RELEASE_MIXTURE_TO_PRE_LAUNTER_TUN_SECOND_TIME");
        $m: Measurer(name == "MEASURER_MASH_TUN", value == 0);
    then
        delete($a);
        System.out.println("STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN_SECOND_TIME");
        insert(new Action("STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN_SECOND_TIME"));
        actionService.sendMessage("STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN_SECOND_TIME");
end

rule "Release mixture to launter tun"
    when
        $a: Action(type == "STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN");
    then
        delete($a);
        System.out.println("RELEASE_MIXTURE_TO_LAUNTER_TUN");
        insert(new Action("RELEASE_MIXTURE_TO_LAUNTER_TUN"));
        actionService.sendMessage("RELEASE_MIXTURE_TO_LAUNTER_TUN");
        System.out.println("phase four started!");
end

rule "Release mixture to launter tun for second time"
    when
        $a: Action(type == "STOP_RELEASING_MIXTURE_TO_PRE_LAUNTER_TUN_SECOND_TIME");
        $a2: Action(type == "STOP_RELEASING_BACK_MIXTURE_TO_PRE_LAUNTER_TUN");
        $m: Measurer(name == "MEASURER_LAUNTER_TUN", value == 0);
        $m2: Measurer(name == "MEASURER_MASH_TUN", value == 0);
    then
        delete($a);
        delete($a2);
        System.out.println("RELEASE_MIXTURE_TO_LAUNTER_TUN_SECOND_TIME");
        insert(new Action("RELEASE_MIXTURE_TO_LAUNTER_TUN_SECOND_TIME"));
        actionService.sendMessage("RELEASE_MIXTURE_TO_LAUNTER_TUN_SECOND_TIME");
        System.out.println("phase four started!");
end
